#!/usr/bin/env bash
# Displays numbers 1-20 "good luck" "bad luck" "China" "Japan" "Italy"
COUNTER=0
while [ $COUNTER -lt 20 ];do
	((COUNTER++))
	echo "$COUNTER"
	case $COUNTER in
	4) echo "bad luck from China";;
	9) echo "bad luck from Japan";;
	17) echo "bad luck from Italy";;
	esac
done
